# Generated by Django 5.1.5 on 2025-01-20 07:46

from django.db import migrations, models
def create_default_user(apps, schema_editor):
    # Get the AppUser model
    AppUser = apps.get_model('app', 'AppUser')

    # Check if a default user already exists, if not, create one
    if not AppUser.objects.filter(user_name='admin').exists():
        AppUser.objects.create(
            first_name='Admin',
            last_name='User',
            user_name='admin',
            email='ayush@kugelblits.xyz',
            mobile_no='8003464814',
            password='password',  # Normally you would hash this, but for example purposes, it's plain text
            is_admin=True
        )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('created_on_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_default_user),
    ]
